baseURL: "https://market2csv.pages.dev/"
languageCode: "pt-br"
title: "Market2csv"
theme: "PaperMod"
copyright: "© [Market2csv](https://github.com/caiowirthmann/market2csv)"
googleAnalytics: ""

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: dark
  ShowCodeCopyButtons: true
  disableAnchoredHeadings: true
  homeInfoparams:
    Title: Market2csv
    Content: >

      Ferramenta **open souce gratuita** desenvolvida em Go para extração de dados de anúncios de diversos marketplaces.


      Você pode coletar informações detalhadas como título, descrição, preços, estoque, avaliações, informações do vendedor e ficha técnica dos produtos.


      Fácil de usar, não precisa de login nas contas do marketplace, navegador.


      Compativel tanto com Windows quanto sistemas Unix (Linux, MacOs).

  socialIcons:
    - name: github
    - url: "https://github.com/caiowirthmann/market2csv/"
    - name: discord
    - url: "https://discord.com/users/279083512638734336"
    - name: telegram
    - url: "https://t.me/caiowp"

menu:
  main:
    - identifier: Inicio
      name: Inicio
      url: ""
      weight: 1
    - identifier: Como usar
      name: Como usar
      url: /posts/como-usar/
      weight: 2
    - identifier: Instalação/Download
      name: Instalação / Download
      url: /posts/instalacao/
      weight: 3

    - identifier: Exemplos
      name: Exemplos
      url: /posts/exemplos/
      weight: 4
    - identifier: Limitações
      name: "Limitações"
      url: /posts/limitacoes/
      weight: 5
    - identifier: FAQ e Suporte
      name: FAQ e Suporte
      url: /posts/faq/
      weight: 6
